--------------+----------------------------------------------
 Host IP      | 192.166.0.5
 PyTorch      | 2.4.0a0+git4451b0e
 Torch-SDAA   | 2.0.0
--------------+----------------------------------------------
 SDAA Driver  | 2.0.0 (N/A)
 SDAA Runtime | 2.0.0 (/opt/tecoai/lib64/libsdaart.so)
 SDPTI        | 1.3.1 (/opt/tecoai/lib64/libsdpti.so)
 TecoDNN      | 2.0.0 (/opt/tecoai/lib64/libtecodnn.so)
 TecoBLAS     | 2.0.0 (/opt/tecoai/lib64/libtecoblas.so)
 CustomDNN    | 1.22.0 (/opt/tecoai/lib64/libtecodnn_ext.so)
 TecoRAND     | 1.8.0 (/opt/tecoai/lib64/libtecorand.so)
 TCCL         | 1.21.0 (/opt/tecoai/lib64/libtccl.so)
--------------+----------------------------------------------
/root/miniconda3/envs/acnet/lib/python3.10/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
W0213 10:40:23.260000 140303587571520 torch/distributed/run.py:779] 
W0213 10:40:23.260000 140303587571520 torch/distributed/run.py:779] *****************************************
W0213 10:40:23.260000 140303587571520 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0213 10:40:23.260000 140303587571520 torch/distributed/run.py:779] *****************************************
/root/miniconda3/envs/acnet/bin/python: can't open file '/data/htx/ACNet/PyTorch/contrib/Classification/ACNet-master/scripts/acnet/do_acnet.py': [Errno 2] No such file or directory
/root/miniconda3/envs/acnet/bin/python: can't open file '/data/htx/ACNet/PyTorch/contrib/Classification/ACNet-master/scripts/acnet/do_acnet.py': [Errno 2] No such file or directory
/root/miniconda3/envs/acnet/bin/python: can't open file '/data/htx/ACNet/PyTorch/contrib/Classification/ACNet-master/scripts/acnet/do_acnet.py': [Errno 2] No such file or directory
/root/miniconda3/envs/acnet/bin/python: can't open file '/data/htx/ACNet/PyTorch/contrib/Classification/ACNet-master/scripts/acnet/do_acnet.py': [Errno 2] No such file or directory
E0213 10:40:23.379000 140303587571520 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 246302) of binary: /root/miniconda3/envs/acnet/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/acnet/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/acnet/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/acnet/lib/python3.10/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/root/miniconda3/envs/acnet/lib/python3.10/site-packages/typing_extensions.py", line 2853, in wrapper
    return arg(*args, **kwargs)
  File "/root/miniconda3/envs/acnet/lib/python3.10/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/root/miniconda3/envs/acnet/lib/python3.10/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/root/miniconda3/envs/acnet/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/root/miniconda3/envs/acnet/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/acnet/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
acnet/do_acnet.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-02-13_10:40:23
  host      : 3658867ff3ed
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 246303)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-02-13_10:40:23
  host      : 3658867ff3ed
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 246304)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2025-02-13_10:40:23
  host      : 3658867ff3ed
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 246305)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-02-13_10:40:23
  host      : 3658867ff3ed
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 246302)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
